project_id = "rhshbmleeqfjxcimvufy"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
secure_password_change_enabled = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.create-wompi-payment]
verify_jwt = false

[functions.verify-wompi-payment]
verify_jwt = false

[functions.wompi-webhook]
verify_jwt = false