// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhshbmleeqfjxcimvufy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJoc2hibWxlZXFmanhjaW12dWZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNzYxNDUsImV4cCI6MjA2ODk1MjE0NX0.0dSrn086AndBDyPPhMAvf-7azw45tEpUX8Rsjp7gUto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});